//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BizTbl_MailTemplate
    {
        public BizTbl_MailTemplate()
        {
            this.BizTbl_MailQueue = new HashSet<BizTbl_MailQueue>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string MailParameters { get; set; }
        public string MailFrom { get; set; }
        public string MailTo { get; set; }
        public string MailCC { get; set; }
        public string Description_tr { get; set; }
        public string Subject_tr { get; set; }
        public string Body_tr { get; set; }
        public string Description_en { get; set; }
        public string Subject_en { get; set; }
        public string Body_en { get; set; }
        public string Description_de { get; set; }
        public string Subject_de { get; set; }
        public string Body_de { get; set; }
        public string Description_es { get; set; }
        public string Subject_es { get; set; }
        public string Body_es { get; set; }
        public string Description_fr { get; set; }
        public string Subject_fr { get; set; }
        public string Body_fr { get; set; }
        public string Description_ru { get; set; }
        public string Subject_ru { get; set; }
        public string Body_ru { get; set; }
        public string Description_it { get; set; }
        public string Subject_it { get; set; }
        public string Body_it { get; set; }
        public string Description_ar { get; set; }
        public string Subject_ar { get; set; }
        public string Body_ar { get; set; }
        public string Description_ja { get; set; }
        public string Subject_ja { get; set; }
        public string Body_ja { get; set; }
        public string Description_pt { get; set; }
        public string Subject_pt { get; set; }
        public string Body_pt { get; set; }
        public string Description_zh { get; set; }
        public string Subject_zh { get; set; }
        public string Body_zh { get; set; }
        public bool Active { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual ICollection<BizTbl_MailQueue> BizTbl_MailQueue { get; set; }
        public virtual BizTbl_User BizTbl_User { get; set; }
    }
}
