//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BizTbl_TableColumn
    {
        public int ID { get; set; }
        public int TableID { get; set; }
        public string Name { get; set; }
        public string Caption_tr { get; set; }
        public string Caption_en { get; set; }
        public string Caption_de { get; set; }
        public string Caption_es { get; set; }
        public string Caption_fr { get; set; }
        public string Caption_ru { get; set; }
        public string Caption_it { get; set; }
        public string Caption_ar { get; set; }
        public string Caption_ja { get; set; }
        public string Caption_pt { get; set; }
        public string Caption_zh { get; set; }
        public string Description { get; set; }
        public bool Multilingual { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual BizTbl_Table BizTbl_Table { get; set; }
        public virtual BizTbl_User BizTbl_User { get; set; }
    }
}
