//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BizTbl_PageControl
    {
        public int ID { get; set; }
        public int PageID { get; set; }
        public string Code { get; set; }
        public string Text_tr { get; set; }
        public string Text_en { get; set; }
        public string Text_de { get; set; }
        public string Text_es { get; set; }
        public string Text_fr { get; set; }
        public string Text_ru { get; set; }
        public string Text_it { get; set; }
        public string Text_ar { get; set; }
        public string Text_ja { get; set; }
        public string Text_pt { get; set; }
        public string Text_zh { get; set; }
        public string Description_tr { get; set; }
        public string Description_en { get; set; }
        public string Description_de { get; set; }
        public string Description_es { get; set; }
        public string Description_fr { get; set; }
        public string Description_ru { get; set; }
        public string Description_it { get; set; }
        public string Description_ar { get; set; }
        public string Description_ja { get; set; }
        public string Description_pt { get; set; }
        public string Description_zh { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual BizTbl_Page BizTbl_Page { get; set; }
        public virtual BizTbl_User BizTbl_User { get; set; }
    }
}
