//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BizTbl_SecurityGroupRight
    {
        public int ID { get; set; }
        public int SecurityGroupID { get; set; }
        public int SecurityID { get; set; }
        public bool HasRight { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual BizTbl_Security BizTbl_Security { get; set; }
        public virtual BizTbl_SecurityGroup BizTbl_SecurityGroup { get; set; }
        public virtual BizTbl_User BizTbl_User { get; set; }
    }
}
