//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BizTbl_Error
    {
        public int ID { get; set; }
        public string Page { get; set; }
        public string Message { get; set; }
        public string Detail { get; set; }
        public System.DateTime Date { get; set; }
        public string IPAddress { get; set; }
    }
}
