//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BizTbl_UserOperation
    {
        public long ID { get; set; }
        public long UserID { get; set; }
        public System.DateTime Date { get; set; }
        public int OperationTypeID { get; set; }
        public Nullable<int> PartID { get; set; }
        public Nullable<long> RecordID { get; set; }
        public string IPAddress { get; set; }
        public Nullable<long> UserSessionID { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual BizTbl_UserSession BizTbl_UserSession { get; set; }
        public virtual TB_Part TB_Part { get; set; }
        public virtual TB_TypeOperation TB_TypeOperation { get; set; }
    }
}
