//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BizTbl_UserHistory
    {
        public long ID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<int> SalutationTypeID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<long> RegionID { get; set; }
        public Nullable<long> CityID { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string PostCode { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> FirmID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<bool> PromotionalEmail { get; set; }
        public string VerificationCode { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> Genius { get; set; }
        public Nullable<bool> Locked { get; set; }
        public Nullable<bool> Active { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public long CreateUserID { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime LogDateTime { get; set; }
        public long LogUserID { get; set; }
    
        public virtual TB_Region TB_Region { get; set; }
        public virtual TB_Country TB_Country { get; set; }
        public virtual TB_Region TB_Region1 { get; set; }
        public virtual TB_TypeSalutation TB_TypeSalutation { get; set; }
        public virtual TB_Firm TB_Firm { get; set; }
        public virtual TB_TypeStatus TB_TypeStatus { get; set; }
    }
}
