//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BizTbl_UserSession
    {
        public BizTbl_UserSession()
        {
            this.BizTbl_UserOperation = new HashSet<BizTbl_UserOperation>();
            this.TB_Reservation = new HashSet<TB_Reservation>();
        }
    
        public long ID { get; set; }
        public string Code { get; set; }
        public long UserID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime OpDateTime { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual TB_Country TB_Country { get; set; }
        public virtual ICollection<BizTbl_UserOperation> BizTbl_UserOperation { get; set; }
        public virtual ICollection<TB_Reservation> TB_Reservation { get; set; }
    }
}
