//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BizTbl_SecurityGroup
    {
        public BizTbl_SecurityGroup()
        {
            this.BizTbl_SecurityGroupRight = new HashSet<BizTbl_SecurityGroupRight>();
            this.BizTbl_TableSecurityGroupRight = new HashSet<BizTbl_TableSecurityGroupRight>();
            this.BizTbl_UserRight = new HashSet<BizTbl_UserRight>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Description_tr { get; set; }
        public string Description_en { get; set; }
        public string Description_de { get; set; }
        public string Description_es { get; set; }
        public string Description_fr { get; set; }
        public string Description_ru { get; set; }
        public string Description_it { get; set; }
        public string Description_ar { get; set; }
        public string Description_jp { get; set; }
        public short Level { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual ICollection<BizTbl_SecurityGroupRight> BizTbl_SecurityGroupRight { get; set; }
        public virtual ICollection<BizTbl_TableSecurityGroupRight> BizTbl_TableSecurityGroupRight { get; set; }
        public virtual ICollection<BizTbl_UserRight> BizTbl_UserRight { get; set; }
    }
}
