//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    
    public partial class GetHotels_Result5
    {
        public Nullable<int> ID { get; set; }
        public string Name { get; set; }
        public string FirmName { get; set; }
        public string HotelTypeName { get; set; }
        public string HotelClassName { get; set; }
        public string HotelAccommodationTypeName { get; set; }
        public string HotelChainName { get; set; }
        public string CountryName { get; set; }
        public string RegionName { get; set; }
        public string CityName { get; set; }
        public string MainRegionName { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebAddress { get; set; }
        public string StatusName { get; set; }
        public string Active { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<System.DateTime> OpDateTime { get; set; }
        public string FirmID { get; set; }
        public string CountryID { get; set; }
        public string RegionID { get; set; }
        public string CityID { get; set; }
        public string CurrencyID { get; set; }
        public string RoutingName { get; set; }
        public string HotelAccommodationTypeID { get; set; }
        public string AvailabilityRateUpdate { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string ParentRegionID { get; set; }
    }
}
