//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    
    public partial class GetPenaltyRate_Result1
    {
        public Nullable<int> ID { get; set; }
        public Nullable<int> PartID { get; set; }
        public string Name { get; set; }
    }
}
