//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Attribute
    {
        public TB_Attribute()
        {
            this.TB_Attribute1 = new HashSet<TB_Attribute>();
            this.TB_HotelRoomAttribute = new HashSet<TB_HotelRoomAttribute>();
            this.TB_TourAttribute = new HashSet<TB_TourAttribute>();
            this.TB_HotelAttribute = new HashSet<TB_HotelAttribute>();
        }
    
        public int ID { get; set; }
        public int PartID { get; set; }
        public int AttributeTypeID { get; set; }
        public Nullable<int> AttributeHeaderID { get; set; }
        public string Name_tr { get; set; }
        public string Name_en { get; set; }
        public string Name_de { get; set; }
        public string Name_es { get; set; }
        public string Name_fr { get; set; }
        public string Name_ru { get; set; }
        public string Name_it { get; set; }
        public string Name_ar { get; set; }
        public string Name_ja { get; set; }
        public string Name_pt { get; set; }
        public string Name_zh { get; set; }
        public string Description_tr { get; set; }
        public string Description_en { get; set; }
        public string Description_de { get; set; }
        public string Description_es { get; set; }
        public string Description_fr { get; set; }
        public string Description_ru { get; set; }
        public string Description_it { get; set; }
        public string Description_ar { get; set; }
        public string Description_ja { get; set; }
        public string Description_pt { get; set; }
        public string Description_zh { get; set; }
        public Nullable<int> DataTypeID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string MinValue { get; set; }
        public string MaxValue { get; set; }
        public Nullable<bool> Chargeable { get; set; }
        public Nullable<bool> IsFilter { get; set; }
        public Nullable<short> Sort { get; set; }
        public bool Active { get; set; }
        public Nullable<int> RelatedAttributeID { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
        public string Icons { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual ICollection<TB_Attribute> TB_Attribute1 { get; set; }
        public virtual TB_Attribute TB_Attribute2 { get; set; }
        public virtual TB_AttributeHeader TB_AttributeHeader { get; set; }
        public virtual TB_Unit TB_Unit { get; set; }
        public virtual TB_Part TB_Part { get; set; }
        public virtual ICollection<TB_HotelRoomAttribute> TB_HotelRoomAttribute { get; set; }
        public virtual TB_TypeAttribute TB_TypeAttribute { get; set; }
        public virtual ICollection<TB_TourAttribute> TB_TourAttribute { get; set; }
        public virtual ICollection<TB_HotelAttribute> TB_HotelAttribute { get; set; }
    }
}
