//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Bank
    {
        public int ID { get; set; }
        public int CountryID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public string BankName { get; set; }
        public string BankBranchName { get; set; }
        public string BankAccountNumber { get; set; }
        public string IBAN { get; set; }
        public string SWIFT { get; set; }
        public string OtherInfo { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual TB_Country TB_Country { get; set; }
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual TB_Currency TB_Currency { get; set; }
    }
}
