//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EmailList
    {
        public long ID { get; set; }
        public string Email { get; set; }
        public string IPAddress { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public System.DateTime OpDateTime { get; set; }
    }
}
