//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Firm
    {
        public TB_Firm()
        {
            this.BizTbl_User = new HashSet<BizTbl_User>();
            this.BizTbl_UserHistory = new HashSet<BizTbl_UserHistory>();
            this.TB_FirmRequest = new HashSet<TB_FirmRequest>();
            this.TB_BusinessPartner = new HashSet<TB_BusinessPartner>();
            this.TB_Hotel = new HashSet<TB_Hotel>();
            this.TB_Invoice = new HashSet<TB_Invoice>();
            this.TB_Reservation = new HashSet<TB_Reservation>();
            this.TB_DealReservation = new HashSet<TB_DealReservation>();
            this.TB_TourReservation = new HashSet<TB_TourReservation>();
            this.TB_TransferReservation = new HashSet<TB_TransferReservation>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<long> RegionID { get; set; }
        public Nullable<long> CityID { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string PostCode { get; set; }
        public string Email { get; set; }
        public string TaxDepartment { get; set; }
        public string TaxNo { get; set; }
        public Nullable<int> ContactPersonSalutationTypeID { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactPersonSurname { get; set; }
        public string ContactPersonPosition { get; set; }
        public string ContactPersonPhone { get; set; }
        public string ContactPersonEmail { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<bool> Active { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public long CreateUserID { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public Nullable<long> OpUserID { get; set; }
        public string IPAddress { get; set; }
        public string AccountsPersonName { get; set; }
        public string AccountsPersonEmail { get; set; }
        public string AccountsPersonPhone { get; set; }
        public string AccountsPersonFax { get; set; }
        public string ReservationPersonName { get; set; }
        public string ReservationPersonEmail { get; set; }
        public string ReservationPersonPhone { get; set; }
        public string ReservationPersonFax { get; set; }
    
        public virtual ICollection<BizTbl_User> BizTbl_User { get; set; }
        public virtual BizTbl_User BizTbl_User1 { get; set; }
        public virtual BizTbl_User BizTbl_User2 { get; set; }
        public virtual ICollection<BizTbl_UserHistory> BizTbl_UserHistory { get; set; }
        public virtual TB_Country TB_Country { get; set; }
        public virtual TB_Region TB_Region { get; set; }
        public virtual TB_Region TB_Region1 { get; set; }
        public virtual TB_TypeSalutation TB_TypeSalutation { get; set; }
        public virtual TB_TypeStatus TB_TypeStatus { get; set; }
        public virtual ICollection<TB_FirmRequest> TB_FirmRequest { get; set; }
        public virtual ICollection<TB_BusinessPartner> TB_BusinessPartner { get; set; }
        public virtual ICollection<TB_Hotel> TB_Hotel { get; set; }
        public virtual ICollection<TB_Invoice> TB_Invoice { get; set; }
        public virtual ICollection<TB_Reservation> TB_Reservation { get; set; }
        public virtual ICollection<TB_DealReservation> TB_DealReservation { get; set; }
        public virtual ICollection<TB_TourReservation> TB_TourReservation { get; set; }
        public virtual ICollection<TB_TransferReservation> TB_TransferReservation { get; set; }
    }
}
