//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_FAQ
    {
        public int ID { get; set; }
        public string Question_tr { get; set; }
        public string Question_en { get; set; }
        public string Question_de { get; set; }
        public string Question_es { get; set; }
        public string Question_fr { get; set; }
        public string Question_ru { get; set; }
        public string Question_it { get; set; }
        public string Question_ar { get; set; }
        public string Question_ja { get; set; }
        public string Question_pt { get; set; }
        public string Question_zh { get; set; }
        public string Answer_tr { get; set; }
        public string Answer_en { get; set; }
        public string Answer_de { get; set; }
        public string Answer_es { get; set; }
        public string Answer_fr { get; set; }
        public string Answer_ru { get; set; }
        public string Answer_it { get; set; }
        public string Answer_ar { get; set; }
        public string Answer_ja { get; set; }
        public string Answer_pt { get; set; }
        public string Answer_zh { get; set; }
        public int Sort { get; set; }
        public bool Active { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
    }
}
