//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_FirmRequest
    {
        public long ID { get; set; }
        public int FirmID { get; set; }
        public int RequestTypeID { get; set; }
        public Nullable<long> ReservationID { get; set; }
        public int FirmRequestStatusID { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public long CreateUserID { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
        public string IPAddress { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual BizTbl_User BizTbl_User1 { get; set; }
        public virtual TB_Firm TB_Firm { get; set; }
        public virtual TB_TypeFirmRequest TB_TypeFirmRequest { get; set; }
        public virtual TB_TypeFirmRequestStatus TB_TypeFirmRequestStatus { get; set; }
        public virtual TB_Reservation TB_Reservation { get; set; }
    }
}
