//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HotelRoomBed
    {
        public int ID { get; set; }
        public int OptionNo { get; set; }
        public int HotelRoomID { get; set; }
        public int BedTypeID { get; set; }
        public int Count { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual TB_HotelRoom TB_HotelRoom { get; set; }
        public virtual TB_TypeBed TB_TypeBed { get; set; }
    }
}
