//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HotelReservationRate
    {
        public int ID { get; set; }
        public long HotelReservationID { get; set; }
        public Nullable<int> DateID { get; set; }
        public Nullable<decimal> RoomPrice { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<System.DateTime> CancelDateTime { get; set; }
        public Nullable<bool> Active { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual TB_Currency TB_Currency { get; set; }
        public virtual TB_Date TB_Date { get; set; }
        public virtual TB_HotelReservation TB_HotelReservation { get; set; }
    }
}
