//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HotelPromotion
    {
        public TB_HotelPromotion()
        {
            this.TB_HotelPromotionFreebie = new HashSet<TB_HotelPromotionFreebie>();
            this.TB_HotelPromotionRoom = new HashSet<TB_HotelPromotionRoom>();
        }
    
        public int ID { get; set; }
        public int HotelID { get; set; }
        public int PromotionID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<bool> HasDiscount { get; set; }
        public Nullable<int> DiscountPercentage { get; set; }
        public Nullable<System.DateTime> AccommodationStartDate { get; set; }
        public Nullable<System.DateTime> AccommodationEndDate { get; set; }
        public string DayID { get; set; }
        public Nullable<int> DayCount { get; set; }
        public Nullable<int> EarlyBookerMargin { get; set; }
        public Nullable<int> LastMinuteMargin { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string PricePolicyID { get; set; }
        public bool SecretDeal { get; set; }
        public string Region { get; set; }
        public bool ValidForAllRoomTypes { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public long CreateUserID { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual BizTbl_User BizTbl_User1 { get; set; }
        public virtual ICollection<TB_HotelPromotionFreebie> TB_HotelPromotionFreebie { get; set; }
        public virtual ICollection<TB_HotelPromotionRoom> TB_HotelPromotionRoom { get; set; }
        public virtual TB_Promotion TB_Promotion { get; set; }
        public virtual TB_Hotel TB_Hotel { get; set; }
    }
}
