//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HotelAvailability
    {
        public int ID { get; set; }
        public int HotelRoomID { get; set; }
        public int DateID { get; set; }
        public int RoomCount { get; set; }
        public Nullable<bool> CloseToArrival { get; set; }
        public Nullable<bool> CloseToDeparture { get; set; }
        public Nullable<int> MinimumStay { get; set; }
        public Nullable<bool> Closed { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual TB_Date TB_Date { get; set; }
        public virtual TB_HotelRoom TB_HotelRoom { get; set; }
    }
}
