//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Hotel
    {
        public TB_Hotel()
        {
            this.TB_HotelAttribute = new HashSet<TB_HotelAttribute>();
            this.TB_HotelCancelPolicy = new HashSet<TB_HotelCancelPolicy>();
            this.TB_HotelComission = new HashSet<TB_HotelComission>();
            this.TB_HotelCreditCard = new HashSet<TB_HotelCreditCard>();
            this.TB_HotelMinumumAccommodation = new HashSet<TB_HotelMinumumAccommodation>();
            this.TB_HotelPromotion = new HashSet<TB_HotelPromotion>();
            this.TB_HotelPromotionHistory = new HashSet<TB_HotelPromotionHistory>();
            this.TB_HotelRegion = new HashSet<TB_HotelRegion>();
            this.TB_HotelRoom = new HashSet<TB_HotelRoom>();
            this.TB_HotelReservation = new HashSet<TB_HotelReservation>();
        }
    
        public int ID { get; set; }
        public int FirmID { get; set; }
        public int HotelTypeID { get; set; }
        public int HotelClassID { get; set; }
        public Nullable<int> HotelChainID { get; set; }
        public int HotelAccommodationTypeID { get; set; }
        public int CountryID { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<long> RegionID { get; set; }
        public Nullable<long> MainRegionID { get; set; }
        public string Name { get; set; }
        public string Description_tr { get; set; }
        public string Description_en { get; set; }
        public string Description_de { get; set; }
        public string Description_es { get; set; }
        public string Description_fr { get; set; }
        public string Description_ru { get; set; }
        public string Description_it { get; set; }
        public string Description_ar { get; set; }
        public string Description_ja { get; set; }
        public string Description_pt { get; set; }
        public string Description_zh { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string PostCode { get; set; }
        public Nullable<short> RoomCount { get; set; }
        public string WebAddress { get; set; }
        public string Email { get; set; }
        public string CheckinStart { get; set; }
        public string CheckinEnd { get; set; }
        public string CheckoutStart { get; set; }
        public string CheckoutEnd { get; set; }
        public Nullable<int> FloorCount { get; set; }
        public Nullable<int> BuiltYear { get; set; }
        public Nullable<int> RenovationYear { get; set; }
        public Nullable<long> HitCount { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<bool> IsPreferred { get; set; }
        public Nullable<bool> IsMainPageDisplay { get; set; }
        public Nullable<int> MainPageDisplaySort { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> MapZoomIndex { get; set; }
        public Nullable<long> ClosestAirportID { get; set; }
        public Nullable<decimal> ClosestAirportDistance { get; set; }
        public Nullable<decimal> ReviewPoint { get; set; }
        public Nullable<bool> ShowOffline { get; set; }
        public Nullable<bool> CreditCardNotRequired { get; set; }
        public Nullable<int> CultureID { get; set; }
        public string RoutingName { get; set; }
        public Nullable<bool> IsSecret { get; set; }
        public Nullable<bool> IsValueDeal { get; set; }
        public Nullable<System.DateTime> LatestBookingDate { get; set; }
        public Nullable<int> LatestBookingCountryID { get; set; }
        public Nullable<int> ChannelManagerID { get; set; }
        public Nullable<bool> AvailabilityRateUpdate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<long> CreateUserID { get; set; }
        public Nullable<System.DateTime> OpDateTime { get; set; }
        public Nullable<long> OpUserID { get; set; }
        public string IPAddress { get; set; }
    
        public virtual BizTbl_Culture BizTbl_Culture { get; set; }
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual BizTbl_User BizTbl_User1 { get; set; }
        public virtual TB_ChannelManager TB_ChannelManager { get; set; }
        public virtual TB_Country TB_Country { get; set; }
        public virtual TB_Country TB_Country1 { get; set; }
        public virtual TB_Currency TB_Currency { get; set; }
        public virtual TB_Firm TB_Firm { get; set; }
        public virtual TB_Region TB_Region { get; set; }
        public virtual TB_Region TB_Region1 { get; set; }
        public virtual TB_Region TB_Region2 { get; set; }
        public virtual TB_Region TB_Region3 { get; set; }
        public virtual TB_TypeHotel TB_TypeHotel { get; set; }
        public virtual TB_TypeHotelAccommodation TB_TypeHotelAccommodation { get; set; }
        public virtual TB_TypeHotelChain TB_TypeHotelChain { get; set; }
        public virtual TB_TypeHotelClass TB_TypeHotelClass { get; set; }
        public virtual TB_TypeStatus TB_TypeStatus { get; set; }
        public virtual ICollection<TB_HotelAttribute> TB_HotelAttribute { get; set; }
        public virtual ICollection<TB_HotelCancelPolicy> TB_HotelCancelPolicy { get; set; }
        public virtual ICollection<TB_HotelComission> TB_HotelComission { get; set; }
        public virtual ICollection<TB_HotelCreditCard> TB_HotelCreditCard { get; set; }
        public virtual ICollection<TB_HotelMinumumAccommodation> TB_HotelMinumumAccommodation { get; set; }
        public virtual ICollection<TB_HotelPromotion> TB_HotelPromotion { get; set; }
        public virtual ICollection<TB_HotelPromotionHistory> TB_HotelPromotionHistory { get; set; }
        public virtual ICollection<TB_HotelRegion> TB_HotelRegion { get; set; }
        public virtual ICollection<TB_HotelRoom> TB_HotelRoom { get; set; }
        public virtual ICollection<TB_HotelReservation> TB_HotelReservation { get; set; }
    }
}
