//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Invoice
    {
        public int ID { get; set; }
        public int FirmID { get; set; }
        public int InvoiceStatusID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int PeriodID { get; set; }
        public System.DateTime DueDate { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual TB_Currency TB_Currency { get; set; }
        public virtual TB_Firm TB_Firm { get; set; }
        public virtual TB_Period TB_Period { get; set; }
        public virtual TB_TypeInvoiceStatus TB_TypeInvoiceStatus { get; set; }
    }
}
