//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LatestNews
    {
        public int ID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string Title_tr { get; set; }
        public string Title_en { get; set; }
        public string Title_de { get; set; }
        public string Title_es { get; set; }
        public string Title_fr { get; set; }
        public string Title_ru { get; set; }
        public string Title_it { get; set; }
        public string Title_ar { get; set; }
        public string Title_ja { get; set; }
        public string Title_pt { get; set; }
        public string Title_zh { get; set; }
        public string Description_tr { get; set; }
        public string Description_en { get; set; }
        public string Description_de { get; set; }
        public string Description_es { get; set; }
        public string Description_fr { get; set; }
        public string Description_ru { get; set; }
        public string Description_it { get; set; }
        public string Description_ar { get; set; }
        public string Description_ja { get; set; }
        public string Description_pt { get; set; }
        public string Description_zh { get; set; }
        public string PostImage { get; set; }
        public string Travel { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<System.DateTime> Updateddate { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
