//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Message
    {
        public long ID { get; set; }
        public int MessageSubjectTypeID { get; set; }
        public int MessageStatusID { get; set; }
        public Nullable<int> SalutationTypeID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int CountryID { get; set; }
        public string Text { get; set; }
        public bool Active { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual TB_Country TB_Country { get; set; }
        public virtual TB_TypeMessageStatus TB_TypeMessageStatus { get; set; }
        public virtual TB_TypeMessageSubject TB_TypeMessageSubject { get; set; }
        public virtual TB_TypeSalutation TB_TypeSalutation { get; set; }
    }
}
