//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Region
    {
        public TB_Region()
        {
            this.BizTbl_User = new HashSet<BizTbl_User>();
            this.BizTbl_User1 = new HashSet<BizTbl_User>();
            this.BizTbl_UserHistory = new HashSet<BizTbl_UserHistory>();
            this.BizTbl_UserHistory1 = new HashSet<BizTbl_UserHistory>();
            this.TB_Firm = new HashSet<TB_Firm>();
            this.TB_Firm1 = new HashSet<TB_Firm>();
            this.TB_TypeHotelChain = new HashSet<TB_TypeHotelChain>();
            this.TB_HotelRegion = new HashSet<TB_HotelRegion>();
            this.TB_Transfer = new HashSet<TB_Transfer>();
            this.TB_Transfer1 = new HashSet<TB_Transfer>();
            this.TB_BusinessPartnerRegion = new HashSet<TB_BusinessPartnerRegion>();
            this.TB_Tour = new HashSet<TB_Tour>();
            this.TB_BusinessPartner = new HashSet<TB_BusinessPartner>();
            this.TB_BusinessPartner1 = new HashSet<TB_BusinessPartner>();
            this.TB_Deal = new HashSet<TB_Deal>();
            this.TB_TourRegion = new HashSet<TB_TourRegion>();
            this.TB_Promotion = new HashSet<TB_Promotion>();
            this.TB_Hotel = new HashSet<TB_Hotel>();
            this.TB_Hotel1 = new HashSet<TB_Hotel>();
            this.TB_Hotel2 = new HashSet<TB_Hotel>();
            this.TB_Hotel3 = new HashSet<TB_Hotel>();
        }
    
        public long ID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<long> ParentID { get; set; }
        public Nullable<long> SecondParentID { get; set; }
        public string RegionType { get; set; }
        public string SubRegionType { get; set; }
        public string Name { get; set; }
        public string NameASCII { get; set; }
        public string Name_tr { get; set; }
        public string Name_en { get; set; }
        public string Name_de { get; set; }
        public string Name_es { get; set; }
        public string Name_fr { get; set; }
        public string Name_ru { get; set; }
        public string Name_it { get; set; }
        public string Name_ar { get; set; }
        public string Name_ja { get; set; }
        public string Name_pt { get; set; }
        public string Name_zh { get; set; }
        public string Code { get; set; }
        public Nullable<long> Population { get; set; }
        public Nullable<bool> IsIncludedInDestinationSearch { get; set; }
        public Nullable<bool> IsCity { get; set; }
        public bool IsPopular { get; set; }
        public bool IsFilter { get; set; }
        public bool IsMainPageDisplay { get; set; }
        public Nullable<int> MainPageDisplaySort { get; set; }
        public Nullable<bool> HasCityTax { get; set; }
        public Nullable<long> HitCount { get; set; }
        public Nullable<short> Sort { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> MapZoomIndex { get; set; }
        public bool Active { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
        public string Msgtopdest { get; set; }
        public string Msgtopdest_en { get; set; }
        public string Msgtopdest_ar { get; set; }
    
        public virtual TB_Country TB_Country { get; set; }
        public virtual ICollection<BizTbl_User> BizTbl_User { get; set; }
        public virtual ICollection<BizTbl_User> BizTbl_User1 { get; set; }
        public virtual BizTbl_User BizTbl_User2 { get; set; }
        public virtual ICollection<BizTbl_UserHistory> BizTbl_UserHistory { get; set; }
        public virtual ICollection<BizTbl_UserHistory> BizTbl_UserHistory1 { get; set; }
        public virtual ICollection<TB_Firm> TB_Firm { get; set; }
        public virtual ICollection<TB_Firm> TB_Firm1 { get; set; }
        public virtual ICollection<TB_TypeHotelChain> TB_TypeHotelChain { get; set; }
        public virtual ICollection<TB_HotelRegion> TB_HotelRegion { get; set; }
        public virtual ICollection<TB_Transfer> TB_Transfer { get; set; }
        public virtual ICollection<TB_Transfer> TB_Transfer1 { get; set; }
        public virtual ICollection<TB_BusinessPartnerRegion> TB_BusinessPartnerRegion { get; set; }
        public virtual ICollection<TB_Tour> TB_Tour { get; set; }
        public virtual ICollection<TB_BusinessPartner> TB_BusinessPartner { get; set; }
        public virtual ICollection<TB_BusinessPartner> TB_BusinessPartner1 { get; set; }
        public virtual ICollection<TB_Deal> TB_Deal { get; set; }
        public virtual ICollection<TB_TourRegion> TB_TourRegion { get; set; }
        public virtual ICollection<TB_Promotion> TB_Promotion { get; set; }
        public virtual ICollection<TB_Hotel> TB_Hotel { get; set; }
        public virtual ICollection<TB_Hotel> TB_Hotel1 { get; set; }
        public virtual ICollection<TB_Hotel> TB_Hotel2 { get; set; }
        public virtual ICollection<TB_Hotel> TB_Hotel3 { get; set; }
    }
}
