//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Transfer
    {
        public TB_Transfer()
        {
            this.TB_TransferReservation = new HashSet<TB_TransferReservation>();
        }
    
        public int ID { get; set; }
        public int BusinessPartnerID { get; set; }
        public int TransferPeriodID { get; set; }
        public int TransferPaxID { get; set; }
        public long DepartureRegionID { get; set; }
        public long DestinationRegionID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public decimal Cost { get; set; }
        public int CostCurrencyID { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<int> DepositCurrencyID { get; set; }
        public Nullable<long> HitCount { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public long CreateUserID { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual BizTbl_User BizTbl_User1 { get; set; }
        public virtual TB_Region TB_Region { get; set; }
        public virtual TB_Region TB_Region1 { get; set; }
        public virtual TB_TransferPeriod TB_TransferPeriod { get; set; }
        public virtual TB_Currency TB_Currency { get; set; }
        public virtual TB_Currency TB_Currency1 { get; set; }
        public virtual TB_Currency TB_Currency2 { get; set; }
        public virtual TB_BusinessPartnerPax TB_BusinessPartnerPax { get; set; }
        public virtual TB_BusinessPartner TB_BusinessPartner { get; set; }
        public virtual ICollection<TB_TransferReservation> TB_TransferReservation { get; set; }
    }
}
