//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TypeCreditCard
    {
        public TB_TypeCreditCard()
        {
            this.TB_HotelCreditCard = new HashSet<TB_HotelCreditCard>();
            this.TB_Reservation = new HashSet<TB_Reservation>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> CVCLength { get; set; }
        public Nullable<int> Sort { get; set; }
        public bool CanBeUsedForReservation { get; set; }
        public bool Active { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual ICollection<TB_HotelCreditCard> TB_HotelCreditCard { get; set; }
        public virtual ICollection<TB_Reservation> TB_Reservation { get; set; }
    }
}
