//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TypeHotelChain
    {
        public TB_TypeHotelChain()
        {
            this.TB_Hotel = new HashSet<TB_Hotel>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<short> Sort { get; set; }
        public Nullable<long> RegionID { get; set; }
        public bool Active { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
        public string Name_pt { get; set; }
        public string Name_zh { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual TB_Region TB_Region { get; set; }
        public virtual ICollection<TB_Hotel> TB_Hotel { get; set; }
    }
}
