//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TransferPeriod
    {
        public TB_TransferPeriod()
        {
            this.TB_Transfer = new HashSet<TB_Transfer>();
        }
    
        public int ID { get; set; }
        public int BusinessPartnerID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Period { get; set; }
        public bool Active { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual ICollection<TB_Transfer> TB_Transfer { get; set; }
        public virtual TB_BusinessPartner TB_BusinessPartner { get; set; }
    }
}
