//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Tour
    {
        public TB_Tour()
        {
            this.TB_TourRegion = new HashSet<TB_TourRegion>();
            this.TB_TourAttribute = new HashSet<TB_TourAttribute>();
            this.TB_TourReservation = new HashSet<TB_TourReservation>();
        }
    
        public int ID { get; set; }
        public int BusinessPartnerID { get; set; }
        public string Code { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Name_tr { get; set; }
        public string Name_en { get; set; }
        public string Name_de { get; set; }
        public string Name_es { get; set; }
        public string Name_fr { get; set; }
        public string Name_ru { get; set; }
        public string Name_it { get; set; }
        public string Name_ar { get; set; }
        public string Name_jp { get; set; }
        public string Description_tr { get; set; }
        public string Description_en { get; set; }
        public string Description_de { get; set; }
        public string Description_es { get; set; }
        public string Description_fr { get; set; }
        public string Description_ru { get; set; }
        public string Description_it { get; set; }
        public string Description_ar { get; set; }
        public string Description_jp { get; set; }
        public string SpecialNote_tr { get; set; }
        public string SpecialNote_en { get; set; }
        public string SpecialNote_de { get; set; }
        public string SpecialNote_es { get; set; }
        public string SpecialNote_fr { get; set; }
        public string SpecialNote_ru { get; set; }
        public string SpecialNote_it { get; set; }
        public string SpecialNote_ar { get; set; }
        public string SpecialNote_jp { get; set; }
        public short Quota { get; set; }
        public int TourFrequencyID { get; set; }
        public Nullable<short> Duration { get; set; }
        public Nullable<int> DurationUnitID { get; set; }
        public string TourStartDateTime { get; set; }
        public long StartRegionID { get; set; }
        public Nullable<int> ChildAge { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public decimal Cost { get; set; }
        public int CostCurrencyID { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<int> DepositCurrencyID { get; set; }
        public Nullable<int> DepositTypeID { get; set; }
        public Nullable<int> BusinessPartnerCancelPolicyID { get; set; }
        public Nullable<bool> CreditCardRequired { get; set; }
        public Nullable<long> HitCount { get; set; }
        public Nullable<bool> IsPopular { get; set; }
        public Nullable<int> Sort { get; set; }
        public string RoutingName { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public long CreateUserID { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
        public string IPAddress { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual BizTbl_User BizTbl_User1 { get; set; }
        public virtual TB_Currency TB_Currency { get; set; }
        public virtual TB_Currency TB_Currency1 { get; set; }
        public virtual TB_Currency TB_Currency2 { get; set; }
        public virtual TB_Region TB_Region { get; set; }
        public virtual TB_TypeDeposit TB_TypeDeposit { get; set; }
        public virtual TB_TypeTourFrequency TB_TypeTourFrequency { get; set; }
        public virtual TB_Unit TB_Unit { get; set; }
        public virtual TB_BusinessPartnerCancelPolicy TB_BusinessPartnerCancelPolicy { get; set; }
        public virtual TB_BusinessPartner TB_BusinessPartner { get; set; }
        public virtual ICollection<TB_TourRegion> TB_TourRegion { get; set; }
        public virtual ICollection<TB_TourAttribute> TB_TourAttribute { get; set; }
        public virtual ICollection<TB_TourReservation> TB_TourReservation { get; set; }
    }
}
