//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TypeStatus
    {
        public TB_TypeStatus()
        {
            this.BizTbl_User = new HashSet<BizTbl_User>();
            this.BizTbl_UserHistory = new HashSet<BizTbl_UserHistory>();
            this.TB_Firm = new HashSet<TB_Firm>();
            this.TB_BusinessPartner = new HashSet<TB_BusinessPartner>();
            this.TB_Hotel = new HashSet<TB_Hotel>();
        }
    
        public int ID { get; set; }
        public string Name_tr { get; set; }
        public string Name_en { get; set; }
        public string Name_de { get; set; }
        public string Name_es { get; set; }
        public string Name_fr { get; set; }
        public string Name_ru { get; set; }
        public string Name_it { get; set; }
        public string Name_ar { get; set; }
        public string Name_ja { get; set; }
        public Nullable<short> Sort { get; set; }
        public bool Active { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
        public string Name_pt { get; set; }
        public string Name_zh { get; set; }
    
        public virtual ICollection<BizTbl_User> BizTbl_User { get; set; }
        public virtual BizTbl_User BizTbl_User1 { get; set; }
        public virtual ICollection<BizTbl_UserHistory> BizTbl_UserHistory { get; set; }
        public virtual ICollection<TB_Firm> TB_Firm { get; set; }
        public virtual ICollection<TB_BusinessPartner> TB_BusinessPartner { get; set; }
        public virtual ICollection<TB_Hotel> TB_Hotel { get; set; }
    }
}
