//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbsExtranetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuditLogs
    {
        public long AuditLogID { get; set; }
        public string Action { get; set; }
        public System.DateTime LogDateTime { get; set; }
        public Nullable<long> UserID { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
